/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Sep  3 15:06:18 2016. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TemperatureMessage_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TemperatureMessage, clientId, clientId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, TemperatureMessage, temperatureValue, clientId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
