# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='',
  serialized_pb=_b('\n\x0eprotocol.proto\"@\n\x12TemperatureMessage\x12\x10\n\x08\x63lientId\x18\x01 \x02(\x05\x12\x18\n\x10temperatureValue\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEMPERATUREMESSAGE = _descriptor.Descriptor(
  name='TemperatureMessage',
  full_name='TemperatureMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='TemperatureMessage.clientId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperatureValue', full_name='TemperatureMessage.temperatureValue', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['TemperatureMessage'] = _TEMPERATUREMESSAGE

TemperatureMessage = _reflection.GeneratedProtocolMessageType('TemperatureMessage', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATUREMESSAGE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureMessage)
  ))
_sym_db.RegisterMessage(TemperatureMessage)


# @@protoc_insertion_point(module_scope)
